### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by rsrcoderplay** [huangjunjie-cs/LDA-GCL#1]
你好，作者，model0, vals, inds = load_pretrain_model_candidate(args.dataset, args.fold, logger=logger)就是这个地方，会报FileNotFoundError: [Errno 2] No such file or directory: 'saved/LightGCN-May-01-2022_10-42-45.pth'这个错误，你的saved文件夹中没有这几个pth文件，麻烦能解决一下吗？

**Comment by huangjunjie-cs** [comment]
感谢您对这个工作的关注。具体的文件我在 [readme](https://github.com/huangjunjie-cs/LDA-GCL#data-split)中应该是有提供，你可以下载一下。或者自己训练一个LightGCN也可以的。

Thank you for your interest in this work. The specific files should be provided in the [readme](https://github.com/huangjunjie-cs/LDA-GCL#data-split), which you can download it [here](https://drive.google.com/drive/folders/19U8XwYgttOqQ1LFlaL8D47c7RMlTWJuU). Alternatively, you can also train a LightGCN model by yourself.
