### ISSUE TITLE
代码运行问题： 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by zzeoZheng** [huangjunjie-cs/LDA-GCL#2]
你好，我按照给出的提示，将与训练模型和数据集下载下来之后，并且按照指令运行模型，报了如下错误，请问是哪里有问题呢？
![image](https://github.com/huangjunjie-cs/LDA-GCL/assets/132974535/29155fbb-e74a-4c9d-91ae-6eb1bbaf2494)

**Comment by huangjunjie-cs** [comment]
你好，我猜测大概率是版本问题，建议切换到1.0.1。

Hello, I guess it may be the reason for Recbole version update. I suggest you shift to my version which is 1.0.1.
